### ISSUE TITLE
bbb-video-download does not handle broken SVG generated by BBB

### ISSUE THREAD

**Issue by ichdasich** [tilmanmoser/bbb-video-download#21]
I just processed a set of recordings with bbb-video-download. In less than 1% of recordings (3/384), the script failed due to broken svg. With 1.0.x, the following error occurred: 

```
HOST logging # cat <id>-<timestamp>.log
processing
Error: Evaluation failed: SyntaxError: Invalid or unexpected token
    at ExecutionContext.evaluateHandle (/opt/bbb-mt/node_modules/puppeteer/lib/ExecutionContext.js:63:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/opt/bbb-mt/node_modules/puppeteer/lib/ExecutionContext.js:46:20)
    at async convertSvg (/opt/bbb-mt/node_modules/svg-to-img/dist/index.js:66:20)
    at async createShapes (/opt/bbb-mt/modules/shapes.js:26:13)
    at async Processor.createAssets (/opt/bbb-mt/modules/processor.js:48:31)
    at async process (/opt/bbb-mt/index.js:54:9)
Error: Evaluation failed: SyntaxError: Invalid or unexpected token
    at ExecutionContext.evaluateHandle (/opt/bbb-mt/node_modules/puppeteer/lib/ExecutionContext.js:63:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/opt/bbb-mt/node_modules/puppeteer/lib/ExecutionContext.js:46:20)
    at async convertSvg (/opt/bbb-mt/node_modules/svg-to-img/dist/index.js:66:20)
    at async createShapes (/opt/bbb-mt/modules/shapes.js:26:13)
    at async Processor.createAssets (/opt/bbb-mt/modules/processor.js:48:31)
    at async process (/opt/bbb-mt/index.js:54:9)
```

Upgrading to the most recent version let's the script simply die (0% CPU usage, but does not terminate). Running shapes.svg through an svg linter (svgcheck from pip) allows for processing (barring #20), but as the linter drops all timestamps, shapes/the presentation/drawings are obviously missing. I can share an affected recording outside of github, if so desired.

**Comment by tilmanmoser** [comment]
The latest version (1.1.0) is not parsing the shapes.svg anymore. It's loaded as is in a chromium browser. So linting the file is not neccessary. If you can watch the bbb presentation in the bbb player, it should work fine. There's a known bug, when desksharing is involved, which I'll fix today or latest tomorrow.

**Comment by ichdasich** [comment]
Ok, thank you; My bad. Closing this then.
