### ISSUE TITLE
Server keep killing the ffmpeg process after while!

### ISSUE THREAD

**Issue by ahmdqader** [tilmanmoser/bbb-video-download#31]
Server killing the ffmpeg process after while!

```
Killed

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Processor.createVideo (/opt/bbb-video-download/modules/processor.js:65:26)
    at async process (/opt/bbb-video-download/index.js:55:9) {
  status: 137,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 66 6d 70 65 67 20 76 65 72 73 69 6f 6e 20 34 2e 32 2e 34 2d 31 75 62 75 6e 74 75 30 2e 31 62 62 62 31 7e 31 36 2e 30 34 2e 31 20 43 6f 70 79 72 69 ... 23014 more bytes>
  ],
  pid: 24212,
  stdout: <Buffer >,
  stderr: <Buffer 66 66 6d 70 65 67 20 76 65 72 73 69 6f 6e 20 34 2e 32 2e 34 2d 31 75 62 75 6e 74 75 30 2e 31 62 62 62 31 7e 31 36 2e 30 34 2e 31 20 43 6f 70 79 72 69 ... 23014 more bytes>
}

```

**Comment by tilmanmoser** [comment]
Hi - in close cooperation with a very kind testuser, I worked several iterations in order to get memory usage under control. My analysis and experiments have shown, that the script only works nicely with large videos, that include desksharing, when it is run in a docker container. This solution was provided with v1.2.1
