### ISSUE TITLE
TypeError: Cannot read property 'isOnlyAudio' of null

### ISSUE THREAD

**Issue by oktab1** [tilmanmoser/bbb-video-download#57]
Hello @tilmanmoser,
Thanks for this enhancement. I'm getting some errors and will appreciate your help resolving the issue. I've followed the guide exactly as documented, the only thing I changed was from `--user 998:998` to `--user=998:998` based on docker documentation. I've tried using both the manual option and `bbb-record --rebuild`, please see below the result in both cases.
1. When I run the command manually for an already published presentation, I get the error below
```
ubuntu@ip-xxx-xx-x-xxx:/opt/bbb-video-download$ sudo -u bigbluebutton docker-compose run --rm --user=998:998 app node index.js -i /var/bigbluebutton/published/presentation/f729564ec72824546f0eab6badd8e9398b4e56cf-1614810834891 -o /var/bigbluebutton/published/presentation/f729564ec72824546f0eab6badd8e9398b4e56cf-1614810834891/video.mp4
[Start] Rendering downloadable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/f729564ec72824546f0eab6badd8e9398b4e56cf-1614810834891', output='/var/bigbluebutton/published/presentation/f729564ec72824546f0eab6badd8e9398b4e56cf-1614810834891/video.mp4'),
  format: 'mp4',
  docker: true
}
[Error] Failed rendering downloable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/f729564ec72824546f0eab6badd8e9398b4e56cf-1614810834891', output='/var/bigbluebutton/published/presentation/f729564ec72824546f0eab6badd8e9398b4e56cf-1614810834891/video.mp4'),
  format: 'mp4',
  docker: true,
  workdir: './tmp/datakDAFEj'
} TypeError: Cannot read property 'isOnlyAudio' of null
    at combinePresentationWithWebcams (/home/bigbluebutton/modules/processor.js:53:33)
    at module.exports.createVideo (/home/bigbluebutton/modules/processor.js:21:29)
    at async run (/home/bigbluebutton/index.js:10:9)
```

2. When I rebuild an existing presentation, the video.mp4 file is not created.
```
root@ip-xxx-xx-x-xxx:/opt/bbb-video-download# bbb-record --rebuild f729564ec72824546f0eab6badd8e9398b4e56cf-1614810834891
```
Any suggestion on how to fix this, preferably the second option so that mp4 videos are published automatically.

Thanks for your help.

**Comment by oktab1** [comment]
Hello @tilmanmoser 
Looking for help with this. I'm still unable to use the script due to the error described above. Can you please advise.

Thank you!

**Comment by tilmanmoser** [comment]
To be honest, I have no clue, how this can happen at all. If the webcams object is null, the code should never reach the line, where it breaks:

```
const combinePresentationWithWebcams = async (presentation, webcams, config) => {
    const video = config.workdir + '/video.mp4'

    if (!presentation && **!webcams**)
        throw new Error('The presentation does not contain any renderable inputs (slides, deskshares or webcams/audio)')
    
    if (presentation && **!webcams**)
        fs.renameSync(presentation.video, video)
    
    if (!presentation && webcams)
        await copyWebcamsVideo(webcams.video, video)
    
    if (presentation && webcams.isOnlyAudio)
        await copyWebcamsAudioToPresentation(presentation, webcams, video)
    else
        await stackWebcamsToPresentation(presentation, webcams, video)

    return getVideoInfo(video)
}
```

Can you provide the presentation data in question to run some tests on it?
