### ISSUE TITLE
2.3 still failing

### ISSUE THREAD

**Issue by lonesomewalker** [tilmanmoser/bbb-video-download#64]
Using the provided script, first of all, there is a permission issue, so setting 777 the tmp folder solves that.

Second, when running manually to debug why it is not working:
```
sudo -u bigbluebutton docker-compose run --rm --user 998:998 app node index.js -i /var/bigbluebutton/published/presentation/f8eb152b2bff59b0455f9bd02b3ae57e97d1d09a-1619419572080 -o /var/bigbluebutton/published/presentation/f8eb152b2bff59b0455f9bd02b3ae57e97d1d09a-1619419572080/video.mp4
WARNING: Error loading config file: /root/.docker/config.json: open /root/.docker/config.json: permission denied
[Start] Rendering downloadable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/f8eb152b2bff59b0455f9bd02b3ae57e97d1d09a-1619419572080', output='/var/bigbluebutton/published/presentation/f8eb152b2bff59b0455f9bd02b3ae57e97d1d09a-1619419572080/video.mp4'),
  format: 'mp4',
  docker: true
}
mv: can't create '/var/bigbluebutton/published/presentation/f8eb152b2bff59b0455f9bd02b3ae57e97d1d09a-1619419572080/video.mp4': Permission denied
[Error] Failed rendering downloable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/f8eb152b2bff59b0455f9bd02b3ae57e97d1d09a-1619419572080', output='/var/bigbluebutton/published/presentation/f8eb152b2bff59b0455f9bd02b3ae57e97d1d09a-1619419572080/video.mp4'),
  format: 'mp4',
  docker: true,
  workdir: './tmp/datacDAope'
} Error: Command failed: mv ./tmp/datacDAope/video.mp4 /var/bigbluebutton/published/presentation/f8eb152b2bff59b0455f9bd02b3ae57e97d1d09a-1619419572080/video.mp4
mv: can't create '/var/bigbluebutton/published/presentation/f8eb152b2bff59b0455f9bd02b3ae57e97d1d09a-1619419572080/video.mp4': Permission denied

    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at moveFile (/home/bigbluebutton/modules/processor.js:101:22)
    at module.exports.createVideo (/home/bigbluebutton/modules/processor.js:34:9)
    at async run (/home/bigbluebutton/index.js:10:9) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 6d 76 3a 20 63 61 6e 27 74 20 63 72 65 61 74 65 20 27 2f 76 61 72 2f 62 69 67 62 6c 75 65 62 75 74 74 6f 6e 2f 70 75 62 6c 69 73 68 65 64 2f 70 72 65 ... 95 more bytes>
  ],
  pid: 824,
  stdout: <Buffer >,
  stderr: <Buffer 6d 76 3a 20 63 61 6e 27 74 20 63 72 65 61 74 65 20 27 2f 76 61 72 2f 62 69 67 62 6c 75 65 62 75 74 74 6f 6e 2f 70 75 62 6c 69 73 68 65 64 2f 70 72 65 ... 95 more bytes>
}
```

**Comment by lonesomewalker** [comment]
Permission issue may result by the fact that 998:998 is somewhat wrong.

Excerpt from /etc/passwd:
```
freeswitch:x:999:998:freeswitch:/opt/freeswitch:/bin/bash
etherpad:x:998:997:etherpad user-daemon:/usr/share/etherpad-lite:/bin/false
bigbluebutton:x:997:996:bigbluebutton:/home/bigbluebutton:/bin/false
```

So, when i get that correctly, the rendering stuff should be done by user/group bigbluebutton, right?
In this case, it is done by group freeswitch [998] and user etherpad [998]

But we should have group 996 and user 997 which resolves to bigbluebutton.
```--user 997:996```

**Comment by tilmanmoser** [comment]
Thanks for pointing that out. The command is an example of usage and misleading when you didn‘t read the part of installing the post publish hook where uid and gid of bbb user are read from /etc/passwd. Will update the readme.

**Comment by lonesomewalker** [comment]
Well, obviously i did read it ;-) and this works at the automated way, but not for older recordings which are preferably rendered one by one in times where the server idles...
