### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mauser8004** [tilmanmoser/bbb-video-download#73]
Good afternoon!
I really like the application.

But unfortunately in some cases it runs into this error.  (When converting older 2.2.XY BBB recordings.)
<pre>
  format: 'mp4',
  docker: true,
  workdir: './tmp/dataDJoKmA'
} Error: Command failed: ffmpeg -hide_banner -loglevel error -f concat -i ./tmp/dataDJoKmA/slides.txt -threads 1 -y -filter_complex "[0:v]fps=24, scale=800:-2[out]" -map '[out]' -strict -2 -crf 22 -pix_fmt yuv420p ./tmp/dataDJoKmA/slides.mp4
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at renderVideo (/home/bigbluebutton/modules/slides.js:317:18)
    at module.exports.renderSlides (/home/bigbluebutton/modules/slides.js:13:15)
    at async module.exports.createPresentationVideo (/home/bigbluebutton/modules/presentation.js:10:20)
    at async module.exports.createVideo (/home/bigbluebutton/modules/processor.js:20:26)
    at async run (/home/bigbluebutton/index.js:10:9) {
  status: null,
  signal: 'SIGKILL',
  output: [ null, <Buffer >, <Buffer > ],
  pid: 112,
  stdout: <Buffer >,
  stderr: <Buffer >
</pre>

sudo -u bigbluebutton docker-compose run --rm --user 997:996 app node index.js -v
WARNING: Error loading config file: /root/.docker/config.json: open /root/.docker/config.json: permission denied
1.2.1

Thank you in advance for your help

**Comment by LiohMoeller** [comment]
Could you take a look in dmesg if you got an oom when this happens?

**Comment by mauser8004** [comment]
Thanks for the reply.
 Yes, unfortunately:
 <pre>
[Wed Nov 10 09:29:51 2021] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/docker/0896162751ea1c82dc7b8953a1501a28bc874df92c648adc8d113fa81a39157c,task=ffmpeg,pid=11714,uid=997
[Wed Nov 10 09:29:51 2021] Out of memory: Killed process 11714 (ffmpeg) total-vm:30171988kB, anon-rss:29994956kB, file-rss:0kB, shmem-rss:0kB, UID:997 pgtables:59068kB oom_score_adj:0
[Wed Nov 10 09:29:51 2021] oom_reaper: reaped process 11714 (ffmpeg), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[Wed Nov 10 09:29:52 2021] br-5c79586cebe2: port 1(vethc64c56f) entered disabled state
[Wed Nov 10 09:29:52 2021] vethe3940a2: renamed from eth0
[Wed Nov 10 09:29:52 2021] br-5c79586cebe2: port 1(vethc64c56f) entered disabled state
[Wed Nov 10 09:29:52 2021] device vethc64c56f left promiscuous mode
[Wed Nov 10 09:29:52 2021] br-5c79586cebe2: port 1(vethc64c56f) entered disabled state

 </pre>
 BBB record : 
  du -sh /var/bigbluebutton/published/presentation/cacbff6be499bd63befa85904c95972b649a8870-1619156818116/
1.1G	/var/bigbluebutton/published/presentation/cacbff6be499bd63befa85904c95972b649a8870-1619156818116/
 VM (azure): 8vcpu 32GB RAM .

**Comment by LiohMoeller** [comment]
I have somehow the same setup and it happens to me as well. Not related to the recording version, though. My recording has been generated on bbb 2.3.

**Comment by mauser8004** [comment]
docker --version
Docker version 20.10.10, build b485636
docker-compose --version
docker-compose version 1.21.2, build a133471

I'll try the next one.:
docker-compose.yml 
...
<pre>
    deploy:
      resources:
        limits:
          memory: 21504m
</pre>

**Comment by LiohMoeller** [comment]
Does not really help here.

**Comment by LiohMoeller** [comment]
To be a bit more specific. If not running Docker in swarm mode, docker-compose --compatibility run can be called using the above flags. Still, the ffmpeg run crashes as soon as it hits the memory limit.

**Comment by mauser8004** [comment]
It looks resolved.
Thank you for your debugging direction.
Azure VM not default swap.
I made a bigger swap file on the system and so it ran without error. (In 4 hours)

**Comment by mauser8004** [comment]
You're right. I'm glad it works now.
