### ISSUE TITLE
ffmpeg Rendering giving error

### ISSUE THREAD

**Issue by Hadi-Raja** [tilmanmoser/bbb-video-download#75]
Hi,
  I got the script to work for a couple of recordings but after that it is giving me continuous error for any recording I am running it for. Here is the error 

`[Error] Failed rendering downloable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/ID', output='/var/bigbluebutton/published/presentation/ID/video.mp4'),
  format: 'mp4',
  docker: true,
  workdir: './tmp/dataMoEDif'
} Error: Command failed: ffmpeg -hide_banner -loglevel error -f concat -i ./tmp/dataMoEDif/slides.txt -threads 1 -y -filter_complex "[0:v]fps=24, scale=800:-2[out]" -map '[out]' -strict -2 -crf 22 -pix_fmt yuv420p ./tmp/dataMoEDif/slides.mp4
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at renderVideo (/home/bigbluebutton/modules/slides.js:317:18)
    at module.exports.renderSlides (/home/bigbluebutton/modules/slides.js:13:15)
    at async module.exports.createPresentationVideo (/home/bigbluebutton/modules/presentation.js:10:20)
    at async module.exports.createVideo (/home/bigbluebutton/modules/processor.js:20:26)
    at async run (/home/bigbluebutton/index.js:10:9) {
  status: null,
  signal: 'SIGKILL',
  output: [ null, <Buffer >, <Buffer > ],
  pid: 117,
  stdout: <Buffer >,
  stderr: <Buffer >
}
`
 Can anyone help me out with it ?
 
 Thanks

**Comment by clement850** [comment]
Hello, exactly the same issue here. Thanks

**Comment by embutidox** [comment]
Same error here.

**Comment by Hadi-Raja** [comment]
@tilmanmoser .. Please can you leave a comment regarding it or some guidance in helping fix this issue is highly appreciated.

Thank you.

**Comment by christmart** [comment]
What is your environment, where you run it?
I see the same problems with bbb-video-download on ubuntu 18 on a BBB 2.4.0 host.
If I process the videos with bbb-video-download on ubuntu 16 on a BBB 2.3.16 host, the processing succeeds.

ffmpeg gets killed from oom-killer:
```
Jan  5 05:52:53 bbb-27-29 kernel: [72337.405981] [20806]   997 20806 14432304 13469022 115712000   905227             0 ffmpeg
Jan  5 05:52:53 bbb-27-29 kernel: [72337.405982] Out of memory: Kill process 20806 (ffmpeg) score 904 or sacrifice child
Jan  5 05:52:53 bbb-27-29 kernel: [72337.406179] Killed process 20806 (ffmpeg) total-vm:57729216kB, anon-rss:53876088kB, file-rss:0kB, shmem-rss:0kB
Jan  5 05:52:54 bbb-27-29 kernel: [72338.557187] oom_reaper: reaped process 20806 (ffmpeg), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by christmart** [comment]
I have no changed the following to make it working again until a real fix is availlable:
```
--- a/src/Dockerfile
+++ b/src/Dockerfile
@@ -1,8 +1,8 @@
-FROM node:12-alpine
+FROM node:12-alpine3.11
```

Why does the newer ffmpeg get all this memory until OOM hits?

**Comment by vahid75** [comment]
I faced same error and oom killer killed the ffmpeg process . thanks to @christmart  for his suggestions. 
I think it is because of ubuntu version. I had two containers with this base image `FROM node:12-alpine`  on both ubuntu 16 and ubuntu 18. old version works correctly but on ubuntu 18 it has error.

**Comment by lonesomewalker** [comment]
Should be re-opened and merged :-|

**Comment by jarrodjay** [comment]
> I have now changed the following to make it working again until a real fix is availlable:
> 
> ```
> --- a/src/Dockerfile
> +++ b/src/Dockerfile
> @@ -1,8 +1,8 @@
> -FROM node:12-alpine
> +FROM node:12-alpine3.11
> ```
> 
> Why does the newer ffmpeg get all this memory until OOM hits?



> I have now changed the following to make it working again until a real fix is availlable:
> 
> ```
> --- a/src/Dockerfile
> +++ b/src/Dockerfile
> @@ -1,8 +1,8 @@
> -FROM node:12-alpine
> +FROM node:12-alpine3.11
> ```
> 
> Why does the newer ffmpeg get all this memory until OOM hits?

Can confirm- this worked perfectly. Before patch, it was using upwards of 20GB of RAM and still dying with OOM. ~1G now for the same video.

**Comment by jarrodjay** [comment]
> I have now changed the following to make it working again until a real fix is availlable:
> 
> ```
> --- a/src/Dockerfile
> +++ b/src/Dockerfile
> @@ -1,8 +1,8 @@
> -FROM node:12-alpine
> +FROM node:12-alpine3.11
> ```
> 
> Why does the newer ffmpeg get all this memory until OOM hits?



> I have now changed the following to make it working again until a real fix is availlable:
> 
> ```
> --- a/src/Dockerfile
> +++ b/src/Dockerfile
> @@ -1,8 +1,8 @@
> -FROM node:12-alpine
> +FROM node:12-alpine3.11
> ```
> 
> Why does the newer ffmpeg get all this memory until OOM hits?

Can confirm- this worked perfectly. Before patch, it was using upwards of 20GB of RAM and still dying with OOM. ~1G now for the same video.
