### ISSUE TITLE
Error in BBB 2.4

### ISSUE THREAD

**Issue by mbernardi82** [tilmanmoser/bbb-video-download#83]
We have recently updated to BBB 2.4 and, not always, but with long meeting, we have this error:

root@ns3109230:/opt/bbb-video-download# docker-compose run --rm --user 997:996 app node index.js -i /var/bigbluebutton/published/presentation/cd716c9b27d8dc4aeb35f9118d8d0dff2f54cba5-1646917178297 -o ./video.mp4
Creating bbb-video-download_app_run ... done
[Start] Rendering downloadable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/cd716c9b27d8dc4aeb35f9118d8d0dff2f54cba5-1646917178297', output='./video.mp4'),
  format: 'mp4',
  docker: true
}
[Error] Failed rendering downloable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/cd716c9b27d8dc4aeb35f9118d8d0dff2f54cba5-1646917178297', output='./video.mp4'),
  format: 'mp4',
  docker: true,
  workdir: './tmp/datapNObgA'
} Error: Command failed: ffmpeg -hide_banner -loglevel error -f concat -i ./tmp/datapNObgA/slides.txt -threads 1 -y -filter_complex "[0:v]fps=24, scale=800:-2[out]" -map '[out]' -strict -2 -crf 22 -pix_fmt yuv420p ./tmp/datapNObgA/slides.mp4
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at renderVideo (/home/bigbluebutton/modules/slides.js:317:18)
    at module.exports.renderSlides (/home/bigbluebutton/modules/slides.js:13:15)
    at async module.exports.createPresentationVideo (/home/bigbluebutton/modules/presentation.js:10:20)
    at async module.exports.createVideo (/home/bigbluebutton/modules/processor.js:20:26)
    at async run (/home/bigbluebutton/index.js:10:9) {
  status: null,
  signal: 'SIGKILL',
  output: [ null, <Buffer >, <Buffer > ],
  pid: 133,
  stdout: <Buffer >,
  stderr: <Buffer >
}

**Comment by defnull** [comment]
Look into your system logs and check if the ffmpeg process was killed by the Kernel OOM killer. If yes, you do not have enough ram. Some versions of ffmpeg seem to consume an absurd amount of memory for this computation.
